config/routes.rb
Rails.application.routes.draw do

  ois = { only: %i( index show ) }

  root 'welcome#index'
  get 'welcome/index'

  resources :titles, only: %i( index )
  resources :instrumentals, ois
  resources :years, ois
  resources :people, ois
  resources :songs, ois do
    get :list_by_date, on: :collection
    get :preview_list_by_date, on: :collection
  end
  resources :singles, ois
  resources :albums, ois
  resources :companies, ois
  resources :prefectures, ois
  resources :halls, ois
  resources :bands, ois
  resources :concerts, ois
  resources :books, ois
  resources :activities, ois
  resources :videos, ois

end

app/models/video.rb
# @!attribute type
#   @return [String] タイプ
# @!attribute device_type
#   @return [Fixnum] デバイスタイプ
# @!attribute title_id
#   @return [Fixnum] タイトルID
# @!attribute date
#   @return [Date] 日付
# @!attribute minutes
#   @return [Fixnum] 分
# @!attribute seconds
#   @return [Fixnum] 秒
# @!attribute sort_order
#   @return [Fixnum] 並び順
# @!attribute number
#   @return [String] 番号
# @!attribute year_id
#   @return [Fixnum] 年ID
# @!attribute singer_id
#   @return [Fixnum] シンガーID
# @!attribute j_comment
#   @return [String] 日本語コメント
# @!attribute e_comment
#   @return [String] 英語コメント

class Video < Device
  include Name

  VideoStr2Num = { live_video: 1, cdv: 2, video_clip: 4, video_clips: 8, live_document_and_clip: 16 }
  VideoNum2Str = VideoStr2Num.invert

  # @return [Array<SongList>] 対応する曲リスト一覧
  has_many :song_lists, foreign_key: :device_id, dependent: :destroy

  def self.num2str
    VideoNum2Str
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @device_type = params[:device_type].try(:to_i) || 1
    @videos = Video.device_type_value_has(@device_type).include_title.include_singer.include_event_date.order_date
    @asn = Video::VideoStr2Num
    @ans = Video::VideoNum2Str
  end

  def show
    @video = object_from_params_id Video
    @media = @video.media.include_company.order_sort_order
    @song_lists = @video.song_lists
    @key = params[:key] || 'base_information'
    @device_type = @video.device_types.first
    @videos = Video.device_type_value_has(@device_type).include_title.order_date
    @recorded_at = {}
    case @key
    when 'base_information'
      @singer = @video.singer
      @whole_time = @video.whole_time(@is_ja)
      @song_lists.each do |sl|
        sl.song_list_songs.include_video_to_concert_videos.each do |sls|
          sls.video_to_concert_videos.each do |vcv|
            @recorded_at[vcv.concert_hall] = true
          end
        end
      end
    end
  end
end

app/views/videos/_base_information.html.haml
%table{ default_table_class }
  %tbody
    %tr
      %th= t_ar Device, :name
      %td= device.name(@is_ja)
    %tr
      %th= t_ar Device, :type
      %td
        - if @singer
          = ajax_normal_link object: @singer, ajax_title: @singer.name(@is_ja)
        = device.number
        = (t_ars Video, device.device_type_strs).join(', ')
    %tr
      %th= t_ar Device, :release_date
      %td= year_link device.event_date
    - if @whole_time
      %tr
        %th= t_ar(Device, :whole_time)
        %td= @whole_time
    - unless @recorded_at.keys.empty?
      %tr
        %th= t_ar(Video, :recorded_at)
        %td
          - @recorded_at.keys.each do |ch|
            = year_link ch.event_date
            = ajax_normal_link object: ch.hall
    - comment = device.comment(@is_ja)
    - link = device.link
    - if comment || link
      %tr
        %th= t_ar(Device, :comment)
        %td
          = comment
          = external_or_str link

app/views/videos/_contents.html.haml
%table{ default_table_class }
  %thead
    %tr
      - t_ars(SongListSong, %i( number title lyric music arrangement remarks )).each do |k|
        %th= k
  %tbody
    - song_list.song_list_songs.include_song.order_sort_order.each do |sls|
      %tr
        - song = sls.song
        %td= sls.sort_order
        %td
          - if song
            = ajax_normal_link object: song, ajax_title: song.name(@is_ja)
          - else
            = sls.title(@is_ja)
          = sls.version(@is_ja)
        %td
          - song.lyric_people.each do |p|
            = ajax_normal_link object: p, ajax_title: p.name(@is_ja)
        %td
          - song.music_people.each do |p|
            = ajax_normal_link object: p, ajax_title: p.name(@is_ja)
        %td
          - sls.get_arranges.each do |p|
            = ajax_normal_link object: p, ajax_title: p.name(@is_ja)
        %td
          - sls.video_to_concert_videos.include_concert_song_list_song.each do |vcv|
            - set_list = vcv.concert_song_list_song.song_list
            - concert = set_list.concert
            - hall = vcv.concert_hall.hall
            = t_ar Concert, :recorded_at
            = ajax_normal_link object: hall, ajax_title: hall.name(@is_ja)
            (
            = ajax_normal_link object: concert, ajax_title: concert.name(@is_ja), key: "set_list-#{ set_list.keyword }"
            )

app/views/videos/_index.html.haml
.panel.panel-success
  .panel-heading
    %h4 #{ t '.title' } (#{ t_ar(Video, @ans[@device_type]) })
  .panel-body.table-responsive
    %ul.nav.nav-tabs
      - @ans.each do |key, value|
        - num = Video.device_type_value_has(key).count
        %li{ class_str_or_nil(key == @device_type, "active disabled") }=link_to "#{ t_ar(Video, value) }(#{ num })", videos_path(device_type: key), remote: true
    %table{ default_table_class }
      %thead
        %tr
          - t_ars(Device, %w( number name type release_date remarks )).each do |k|
            %th= k
      %tbody
        - @videos.each_with_index do |video, i|
          - name = video.name(@is_ja)
          - singer = video.singer
          %tr{id: name}
            %td= i+1
            %td= ajax_normal_link object: video, ajax_title: name
            %td
              = ajax_normal_link object: singer, ajax_title: singer.name(@is_ja) if singer
              = video.number
              = t_ar Video, @ans[@device_type]
            %td= year_link video.event_date
            %td= video.comment(@is_ja)

app/views/videos/_show.html.haml
.panel.panel-info
  .panel-heading
    %h4
      = ajax_normal_link show_path: videos_path(device_type: @device_type), ajax_title: t_ars_join(Video, @video.device_type_strs), type: :success
      = @video.name(@is_ja)
      →
      = t_ar Device, @key.split('-').first
  .panel-body.table-responsive
    %ul.nav.nav-tabs
      - keys = %w( base_information )
      - keys << 'media' if @media.count > 0
      - keys.each do |key|
        %li{ class_str_or_nil(@key == key, "active disabled") }
          = link_to t_ar(Device, key), video_path(@video, key: key), remote: true
      - @song_lists.each do |song_list|
        - keyword = song_list.keyword
        - lkeyword = t_ar Medium, keyword
        - key = "contents-#{ keyword }"
        %li{ class_str_or_nil(@key == key, "active disabled") }
          = link_to "#{ t_ar Device, :contents }(#{ lkeyword })", video_path(@video, key: key), remote: true
        - key = "performer-#{ keyword }"
        %li{ class_str_or_nil(@key == key, "active disabled") }
          = link_to "#{ t_ar Device, :performer }(#{ lkeyword })", video_path(@video, key: key), remote: true
    - if @key == 'base_information'
      = render partial: 'base_information', locals: { device: @video }
    - if @key == 'media' && @media.count > 0
      = render partial: '/devices/media'
    - @song_lists.each do |song_list|
      - if @key == "contents-#{ song_list.keyword }"
        = render partial: 'contents', locals: { song_list: song_list }
      - if @key == "performer-#{ song_list.keyword }"
        = render partial: '/devices/performer', locals: { song_list: song_list }
  .panel-footer
    = ajax_normal_link show_path: videos_path(device_type: @device_type), ajax_title: t_ars_join(Video, @video.device_type_strs), type: :success
    - @videos.each do |video|
      - if video == @video
        = link_to video.name(@is_ja), '#', btn_class.merge({ disabled: true })
      - else
        = ajax_normal_link object: video, ajax_title: video.name(@is_ja), key: @key

app/views/videos/index.html.haml
- content_for :title do
  - @title = t ".title"

= render partial: 'index'

app/views/videos/index.js.haml
:plain
  $('#main').html("#{ escape_javascript(render 'index') }")
  $('#je_link').html("#{ escape_javascript(je_link) }")
  $('#url').html("#{ escape_javascript(url_link) }")

app/views/videos/show.html.haml
- content_for :title do
  - @title = "#{ @video.name(@is_ja) } (#{t ".title" })"
= render partial: 'show'

app/views/videos/show.js.haml
:plain
  $('#main').html("#{ escape_javascript(render 'show') }")
  $('#je_link').html("#{ escape_javascript(je_link) }")
  $('#url').html("#{ escape_javascript(url_link) }")