config/routes.rb
Rails.application.routes.draw do

  ois = { only: %i( index show ) }

  root 'welcome#index'
  get 'welcome/index'

  resources :titles, only: %i( index )
  resources :instrumentals, ois
  resources :years, ois
  resources :people, ois
  resources :songs, ois do
    get :list_by_date, on: :collection
    get :preview_list_by_date, on: :collection
  end
  resources :singles, ois
  resources :albums, ois
  resources :companies, ois
  resources :prefectures, ois
  resources :halls, ois
  resources :bands, ois
  resources :concerts, ois
  resources :books, ois
  resources :activities, ois
  resources :videos, ois

end

app/views/shared/_bottom_link_bar.html.haml
.panel.panel-default
  .panel-heading
    = t 'common.links_for_lists'
    - @links = [ albums_path, singles_path, videos_path, concerts_path, songs_path, list_by_date_songs_path, books_path, activities_path, people_path, bands_path, companies_path, years_path, instrumentals_path, prefectures_path, titles_path ]
  .panel-body.table-responsive
    - @links.each do |path|
      = ajax_normal_link show_path: path, ajax_title: title_from_path(path), type: :success

app/views/shared/_links.html.haml
%a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
  = t 'common.lang'
  %span.caret
%ul.dropdown-menu
  - if @is_ja
    %li.disabled= link_to '●日本語', '#'
    %li= link_to '英語', recursive_path(locale: :en), remote: true
  - else
    %li= link_to 'Japanese', recursive_path(locale: :ja), remote: true
    %li.disabled= link_to '●English', '#'

app/views/shared/_top_link_bar.html.haml
.nav.navbar-default.navbar-fixed-top
  .navbar-header
    %button{type: 'button', class: 'navbar-toggle', 'data-toggle' => 'collapse', 'data-target' => '.navbar-responsive-collapse' }
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to t('welcome.index.title'), root_path, class: 'navbar-brand'
  .navbar-collapse.collapse.navbar-responsive-collapse
    %ul.nav.navbar-nav
      %li#je_link= je_link
      %li#url= url_link

= yield :navi if content_for(:navi)

app/views/shared/_url.html.haml
= link_to t('common.url'), recursive_path