config/routes.rb
Rails.application.routes.draw do

  ois = { only: %i( index show ) }

  root 'welcome#index'
  get 'welcome/index'

  resources :titles, only: %i( index )
  resources :instrumentals, ois
  resources :years, ois
  resources :people, ois
  resources :songs, ois do
    get :list_by_date, on: :collection
    get :preview_list_by_date, on: :collection
  end
  resources :singles, ois
  resources :albums, ois
  resources :companies, ois
  resources :prefectures, ois
  resources :halls, ois
  resources :bands, ois
  resources :concerts, ois
  resources :books, ois
  resources :activities, ois
  resources :videos, ois

end

app/models/company.rb
# @!attribute title_id
#   @return [Fixnum] タイトルID

class Company < ActiveRecord::Base
  include Name
  validates :title_id, presence: true
  validates :title_id, uniqueness: true

  # @return [Title] 対応するタイトル
  belongs_to :title

#  # @return [<BBB>] 対応するYYY
#  has_one :bbb

  # @return [Array<Activity>] 対応する活動
  has_many :activities, dependent: :destroy
  # @return [Array<Medium>] 対応するメディア一覧
  has_many :media, dependent: :destroy
  # @return [Array<Book>] 対応するメディア一覧
  has_many :published_books, dependent: :destroy, foreign_key: :publisher_id, class_name: :Book
  # @return [Array<Book>] 対応するメディア一覧
  has_many :selled_books, dependent: :destroy, foreign_key: :seller_id, class_name: :Book

  scope :include_title, -> { includes :title }
  scope :order_yomi, -> { joins(:title).merge(Title.order_yomi) }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.include_title.order_yomi
    @num_of_media = Medium.group(:company_id).count(:id)
    @num_of_published_books = Book.group(:publisher_id).count(:id)
    @num_of_selled_books = Book.group(:seller_id).count(:id)
    @num_of_activities = Activity.group(:company_id).count(:id)
  end

  def show
    @company = object_from_params_id Company
    @devices = {}
    albums = @company.media.only_album.order_code
    @devices['album'] = albums if albums.count > 0
    singles = @company.media.only_single.order_code
    @devices['single'] = singles if singles.count > 0
    books = [ @company.published_books, @company.selled_books ]
    @devices['book'] = books if books.map(&:count).inject(&:+) > 0
    activities = @company.activities
    @devices['activity'] = activities if activities.count > 0
    @key = params[:key] || @devices.keys.first
    @key = @devices.keys.first unless @devices[@key]
    @companies = Company.include_title.order_yomi
  end
end

app/views/companies/_activity.html.haml
%table{ default_table_class }
  %tr
    - t_ars(Activity, %w( number name type )).each do |k|
      %th= k
  - array.include_title.order_sort_order.each_with_index do |activity, i|
    %tr
      %td= i+1
      %td
        = ajax_normal_link object: activity
      %td= t_ar Activity, activity.activity_type

app/views/companies/_book.html.haml
%table{ default_table_class }
  %tr
    - t_ars(Book, %w( number name type code date )).each do |k|
      %th= k
  - array.each do |books|
    - books.include_title.include_event_date.each_with_index do |book, i|
      %tr
        %td= i+1
        %td
          = ajax_normal_link object: book
        %td= t_ar Book, book.book_type
        %td= book.isbn
        %td= year_link book.event_date

app/views/companies/_device.html.haml
%table{ default_table_class }
  %tr
    - t_ars(Device, %w( number name type code date )).each do |k|
      %th= k
  - array.include_device_with_event_date.each_with_index do |m, i|
    %tr
      %td= i+1
      - device = m.device
      %td
        = t_ars_join device.class, device.device_type_strs
        = ajax_normal_link object: device
      %td= t_ar Medium, m.medium_device
      %td= external_or_str m.code
      %td= year_link device.event_date

app/views/companies/_index.html.haml
.panel.panel-success
  .panel-heading
    %h4= t '.title'
  .panel-body.table-responsive
    %table{ default_table_class }
      %thead
        %tr
          - t_ars(Company, %w( number name num_of_media num_of_books num_of_activities )).each do |k|
            %th= k
      %tbody
        - @companies.each_with_index do |company, i|
          - cid = company.id
          - name = company.name(@is_ja)
          %tr{id: name}
            %td= i+1
            %td= ajax_normal_link object: company
            %td= @num_of_media[cid]
            %td= zero_null (@num_of_published_books[cid] || 0) + (@num_of_selled_books[cid] || 0)
            %td= @num_of_activities[cid]

app/views/companies/_show.html.haml
.panel.panel-info
  .panel-heading
    %h4
      = ajax_normal_link_by_title show_path: companies_path, ajax_title: t_ar(Company), type: :success
      = @company.name(@is_ja)
  .panel-body.table-responsive
    %ul.nav.nav-tabs
      - @devices.each do |(key, array)|
        - if array.count > 0
          %li{ class_str_or_nil(@key == key, "active disabled") }
            = link_to t_ar(Company, key), company_path(@company, key: key), remote: true
    - @devices.each do |(key, array)|
      - if array.count > 0
        - if @key == key
          - case key
          - when 'album', 'single'
            = render partial: 'device', locals: { array: array }
          - when 'book'
            = render partial: 'book', locals: { array: array }
          - when 'activity'
            = render partial: 'activity', locals: { array: array }
  .panel-footer
    = ajax_normal_link_by_title show_path: companies_path, ajax_title: t_ar(Company), type: :success
    - @companies.each do |company|
      - if company == @company
        = link_to company.name(@is_ja), '#', btn_class.merge({ disabled: true })
      - else
        = ajax_normal_link object: company, key: @key

app/views/companies/index.html.haml
- content_for :title do
  - @title = t ".title"

= render partial: 'index'

app/views/companies/index.js.haml
:plain
  $('#main').html("#{ escape_javascript(render 'index') }")
  $('#je_link').html("#{ escape_javascript(je_link) }")
  $('#url').html("#{ escape_javascript(url_link) }")

app/views/companies/show.html.haml
- content_for :title do
  - @title = "#{ @company.name(@is_ja) } (#{t ".title" })"

= render partial: 'show'

app/views/companies/show.js.haml
:plain
  $('#main').html("#{ escape_javascript(render 'show') }")
  $('#je_link').html("#{ escape_javascript(je_link) }")
  $('#url').html("#{ escape_javascript(url_link) }")