config/routes.rb
Rails.application.routes.draw do

  ois = { only: %i( index show ) }

  root 'welcome#index'
  get 'welcome/index'

  resources :titles, only: %i( index )
  resources :instrumentals, ois
  resources :years, ois
  resources :people, ois
  resources :songs, ois do
    get :list_by_date, on: :collection
    get :preview_list_by_date, on: :collection
  end
  resources :singles, ois
  resources :albums, ois
  resources :companies, ois
  resources :prefectures, ois
  resources :halls, ois
  resources :bands, ois
  resources :concerts, ois
  resources :books, ois
  resources :activities, ois
  resources :videos, ois

end

app/models/band.rb
# @!attribute title_id
#   @return [Fixnum] タイトルID
# @!attribute j_comment
#   @return [String] 日本語コメント
# @!attribute e_comment
#   @return [String] 英語コメント

class Band < ActiveRecord::Base
  include Name

  validates :title_id, presence: true
  validates :title_id, uniqueness: true

  # @return [Title] 対応するタイトルID
  belongs_to :title

  # @return [Array<Concert>] 対応するコンサート一覧
  has_many :concerts, dependent: :destroy
  # @return [Array<BandMember>] 対応するバンドメンバー一覧
  has_many :band_members, dependent: :destroy

  scope :ids_are, -> array { where arel_table[:id].in array }
  scope :include_title, -> { includes :title }
  scope :order_yomi, -> { joins(:title).merge(Title.order_yomi) }

  def band_members_from_array(array)
    array.each_slice(2) do |i, p|
      band_member_factory(band: self, instrumental_key: i, person_key: p)
    end
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
   @bands = Band.include_title.order_yomi
  end

  def show
    @band = object_from_params_id Band
    @key = params[:key] || 'base_information'
    @bands = Band.include_title.order_yomi
    case @key
    when 'base_information'
      @concerts = @band.concerts.include_title.order_date
    when 'member'
      @band_members_hash = hash_array_from_array(@band.band_members.include_instrumental.order_instrumental_sort_order) { |bm| [ bm.person_id, bm ] }
      @people = Person.ids_are(@band_members_hash.keys).include_title
    end
  end
end

app/views/bands/_base_information.html.haml
%table{ default_table_class }
  %tr
    - t_ars(Band, %w( number concert date )).each do |k|
      %th= k
  - @concerts.each_with_index do |c, i|
    %tr
      %td= i+1
      %td= c.name(@is_ja)
      %td
        = year_link c.from
        - if c.to
          = " - "
          = year_link c.to

app/views/bands/_index.html.haml
.panel.panel-success
  .panel-heading
    %h4= t ".title"
  .panel-body.table-responsive
    %table{ default_table_class }
      %thead
        %tr
          - t_ars(Band, %w( number name remarks )).each do |k|
            %th= k
      %tbody
        - @bands.each_with_index do |band, i|
          - name = band.name(@is_ja)
          %tr{id: name}
            %td= i+1
            %td= ajax_normal_link object: band
            %td= @is_ja ? band.j_comment : band.e_comment

app/views/bands/_member.html.haml
%table{ default_table_class }
  %tr
    - t_ars(Band, %w( member instrumental )).each do |k|
      %th= k
  - @people.each do |p|
    %tr
      %td= ajax_normal_link object: p
      - bms = @band_members_hash[p.id]
      %td
        - bms.each do |bm|
          - instrumental = bm.instrumental
          = ajax_normal_link object: instrumental

app/views/bands/_show.html.haml
.panel.panel-info
  .panel-heading
    %h4
      = ajax_normal_link show_path: bands_path, ajax_title: t_ar(Band), type: :success
      = @band.name(@is_ja)
  .panel-body.table-responsive
    %ul.nav.nav-tabs
      - %w( base_information member ).each do |key|
        %li{ class_str_or_nil(@key == key, 'active disabled') }
          = link_to t_ar(Band, key), band_path(@band, key: key), remote: true
    - if @key == 'base_information'
      = render partial: 'base_information'
    - if @key == 'member'
      = render partial: 'member'
  .panel-footer
    = ajax_normal_link show_path: bands_path, ajax_title: t_ar(Band), type: :success
    - @bands.each do |band|
      - if band == @band
        = link_to band.name(@is_ja), '#', btn_class.merge({ disabled: true })
      - else
        = ajax_normal_link object: band, key: @key

app/views/bands/index.html.haml
- content_for :title do
  - @title = t ".title"
= render partial: 'index'

app/views/bands/index.js.haml
:plain
  $('#main').html("#{ escape_javascript(render 'index') }")
  $('#je_link').html("#{ escape_javascript(je_link) }")
  $('#url').html("#{ escape_javascript(url_link) }")

app/views/bands/show.html.haml
- content_for :title do
  - @title = "#{ @band.name(@is_ja) } (#{t ".title" })"

= render partial: 'show'

app/views/bands/show.js.haml
:plain
  $('#main').html("#{ escape_javascript(render 'show') }")
  $('#je_link').html("#{ escape_javascript(je_link) }")
  $('#url').html("#{ escape_javascript(url_link) }")